### ISSUE TITLE
GPU: Intel GPU(Ze) memory kind in space_create

### ISSUE THREAD

**Issue by minsii** [pmodels/oshmpi#103]
- [x] support Intel GPU memory kind
- [x] add 1 test program

**Comment by pavanbalaji** [comment]
FYI, CUDA needs you to set the device before doing memory allocation too (even though the function itself doesn't take the device argument).  So they are equivalent (except for one function call vs. two function calls).

**Comment by raffenet** [comment]
Oh, I see. So in the tests, the user sets the CUDA device before creating the space. I suppose we can extend `shmemx_space_config_t` to take additional device information for this purpose, like we do with MPL attributes. Still need to modify the internal allocation APIs, but that shouldn't be too bad.

**Comment by minsii** [comment]
@raffenet [here](https://github.com/pmodels/osu-micro-benchmarks-5.6.2-cuda/blob/oshmpi-gpu-space/openshmem/osu_oshm_put.c) is an example for the user program of oshmpi+space+cuda memkind.

We assume the user sets the cuda device, so that `shmemx_space_create` internally calls `cudaMalloc` to allocate buffer on this device.

**Comment by minsii** [comment]
Extending `shmemx_space_config_t` sounds good to me. We want to minimize the device-specific task handled by OSHMPI  - user sets device, OSHMPI only allocates the GPU buffer and passes down to MPI

**Comment by minsii** [comment]
Test added via #107
