### ISSUE TITLE
Cleanup OMPI/UCX jenkins failure

### ISSUE THREAD

**Issue by minsii** [pmodels/oshmpi#62]

**Comment by raffenet** [comment]
OMPI builds look to have a small number of failures, still. MPICH tests are clean since #60.

**Comment by raffenet** [comment]
@minsii by the way, the red Jenkins jobs are blocked because they are unable to fetch the release tarball from your public_html directory. Is there a new location?

**Comment by minsii** [comment]
I deleted them by mistake. Now they are back. But I really should not use my personal website for hosting the tarball. Maybe an easier way is to generate the release tarballs on github. The only issue is that I don't know how to let it trigger `./maint/release.pl` to generate the tarball. Do you have any idea?

**Comment by raffenet** [comment]
I think most projects manually upload the pre-autogen'd release tarballs to GitHub, but we could probably add a Jenkins job or GitHub action to do it based on when a new tag is pushed to the repo.

**Comment by minsii** [comment]
I did not notice that I can manually upload the tarball. I just uploaded them. Can you please use the links at https://github.com/pmodels/oshmpi/releases for the red jenkins jobs? I am going to update the project website too. I will delete the tarballs on my personal page.

**Comment by raffenet** [comment]
Links are updated. 👍

**Comment by raffenet** [comment]
Red jobs are fixed now. Is this job needed or should we remove it? https://pmrs-jenkins.cels.anl.gov/view/oshmpi/job/oshmpi-1.0-testsuite-mpich/

**Comment by minsii** [comment]
I don't think we need the oshmpi-1.0 job anymore. We don't maintain it anyway.

**Comment by raffenet** [comment]
👍  removed. How should we address the failures with Open MPI in the review job? Are there known issues?

**Comment by minsii** [comment]
We do have a few known failures with OpenMPI, but they should be xfailed already. See `SetParseParams` in oshmpi-jenkins-scripts/common.sh (the way we set xfail is a bit weird).

For the current fails, we will need to figure out why they fail

**Comment by minsii** [comment]
All OpenMPI failures are cleared after updating OMPI version and configure option.
- Need to explicitly disable build for OFI (`--without-ofi`). Some failures were caused by the OFI component which is built automatically.
- Need to explicitly disable XPMEM (`--without-xpmem`), otherwise always report warning at execution.
